/**
 * Board mechanics — the ones that are a post-processor on the board.
 *
 * ── Why these are a registry and not one function each ──────────────────────
 * A large share of the interesting mechanics in slots are the same shape: after
 * the board is drawn (or refilled by a cascade), walk it and rewrite some cells.
 * Random wilds, mystery symbols, symbol upgrades, conversions, spawners,
 * guaranteed wilds on a cascade — all of them.
 *
 * Writing a bespoke scaffolder function per mechanic means writing the same
 * splice-and-import plumbing every time, and getting it subtly different every
 * time. So the plumbing lives once in mathScaffold.applyBoardMechanics and each
 * mechanic is DATA: the Python method it needs, where to call it, which
 * evaluators it makes sense on, and what it costs the art team.
 *
 * ── The two rules every entry here obeys ────────────────────────────────────
 * 1. It declares a `boardLifetime`, like every board-writing recipe, so the
 *    cascade knows whether to restore it after a refill. This is the same
 *    abstraction that fixed expanding-wilds-on-a-cascade, applied at the point
 *    a new mechanic is added rather than after it breaks.
 *
 * 2. It states which `winTypes` it is meaningful on, and the spec loader
 *    refuses it elsewhere. A wild-substitution mechanic on scatter-pays would
 *    generate, run, and do nothing — the worst outcome, because it looks like
 *    it works.
 *
 * ── Provenance ──────────────────────────────────────────────────────────────
 * Where a mechanic is associated with a particular game, the entry says so.
 * These are plain-language RULES built from math-sdk primitives. No studio's
 * assets, bundles or source were fetched or inspected.
 */

/**
 * @typedef {object} BoardMechanic
 * @property {string}   id
 * @property {string}   name
 * @property {string}   specKey       the key under `game:` that switches it on
 * @property {string[]} winTypes      evaluators it is meaningful on
 * @property {string}   boardLifetime how long its writes survive
 * @property {string}   seenIn        the game that popularised it, or ''
 * @property {string[]} imports       python modules the emitted method needs
 * @property {(cfg: object) => string} method   the python method source
 * @property {string}   call          the call to splice in
 * @property {'after-draw'|'after-cascade'|'both'} site
 * @property {string[]} [conditions]  distribution condition keys it reads
 */

/** Indent a block of python to a method body. */
const py = (lines) => lines.join('\n');

/** @type {Record<string, BoardMechanic>} */
export const BOARD_MECHANICS = {
	// ── wilds ────────────────────────────────────────────────────────────────
	randomWilds: {
		id: 'random_wild',
		name: 'Random wilds',
		specKey: 'randomWilds',
		winTypes: ['lines', 'ways', 'cluster'],
		boardLifetime: 'this-evaluation',
		seenIn: '',
		imports: [{ module: 'random', plain: true }],
		site: 'after-draw',
		call: 'self.add_random_wilds()',
		art: {
			symbols: 'A wild plus an arrival effect that reads as "added", not "landed".',
			states: ['spawn'],
			animations: ['spawn-in, distinct from a symbol that fell'],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def add_random_wilds(self) -> None:',
				`        """Drop up to ${cfg.max} wilds onto random empty cells.`,
				'',
				'        Generated by stake-forge from game.randomWilds. LOWERS volatility',
				'        and raises the hit rate — a lever for the low end of the range,',
				'        and counterproductive above about 10,000x.',
				'        """',
				`        if self.gametype == self.config.basegame_type and not ${cfg.inBaseGame ? 'False' : 'True'}:`,
				'            return',
				`        count = random.choices(${JSON.stringify(cfg.weights.map(Number))}, weights=${JSON.stringify(cfg.weights.map((_, i) => cfg.weightValues[i]))})[0]`,
				'        placed = 0',
				'        attempts = 0',
				'        # Bounded: a full board of wilds would loop forever looking for a',
				'        # cell that is not already one.',
				'        while placed < count and attempts < 100:',
				'            attempts += 1',
				'            reel = random.randrange(self.config.num_reels)',
				'            row = random.randrange(self.config.num_rows[reel])',
				`            if self.board[reel][row].name == "${cfg.wild}":`,
				'                continue',
				`            if self.board[reel][row].name in ${JSON.stringify(cfg.protected)}:`,
				'                continue',
				`            self.board[reel][row] = self.create_symbol("${cfg.wild}")`,
				'            placed += 1',
			]),
	},

	guaranteedCascadeWild: {
		id: 'guaranteed_wild_per_cascade',
		name: 'Guaranteed wild on every cascade',
		specKey: 'guaranteedCascadeWild',
		winTypes: ['cluster', 'scatter'],
		boardLifetime: 'this-evaluation',
		seenIn: 'Samurai Dogs Unleashed (Twist Gaming)',
		imports: [{ module: 'random', plain: true }],
		site: 'after-cascade',
		call: 'self.ensure_cascade_wild()',
		art: {
			symbols: 'A wild that reads as ARRIVING rather than landing — it is injected, not drawn.',
			states: ['spawn'],
			animations: ['spawn-in on the refill, distinct from a normal fall'],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def ensure_cascade_wild(self) -> None:',
				'        """Guarantee at least one wild among the symbols a cascade drops in.',
				'',
				'        Generated by stake-forge from game.guaranteedCascadeWild. Sustains a',
				'        cascade sequence without making the strips richer, which keeps the',
				'        base board honest while the sequence itself becomes the feature.',
				'',
				'        Raises the chance the next board also wins, which is exactly the',
				'        quantity that has to stay under 1 for a round to terminate — see',
				'        the cascade limits in mathBalance.',
				'        """',
				`        if self.gametype == self.config.basegame_type and not ${cfg.inBaseGame ? 'True' : 'False'}:`,
				'            return',
				'        for reel in self.board:',
				'            for sym in reel:',
				`                if sym.name == "${cfg.wild}":`,
				'                    return',
				'        reel = random.randrange(self.config.num_reels)',
				'        row = random.randrange(self.config.num_rows[reel])',
				`        self.board[reel][row] = self.create_symbol("${cfg.wild}")`,
			]),
	},

	cascadeMultiplier: {
		id: 'progressive_cascade_multiplier',
		name: 'Per-cascade multiplier ladder',
		specKey: 'cascadeMultiplier',
		winTypes: ['cluster', 'scatter'],
		// It writes a NUMBER, not the board — nothing for a refill to restore.
		boardLifetime: 'this-evaluation',
		seenIn: "Gonzo's Quest (NetEnt)",
		imports: [{ module: 'src.events.events', names: ['update_global_mult_event'] }],
		site: 'after-cascade',
		call: 'self.step_cascade_multiplier()',
		// Reset at the start of every spin, because the ladder is per SEQUENCE.
		// Without this the multiplier would carry from one spin of a free-spin
		// round into the next and climb all round, which is a different mechanic.
		init: ['self.cascade_step = 0'],
		art: {
			symbols: [],
			states: [],
			animations: ['a ladder step, one rung per cascade — the rung is the beat'],
			screens: ['a ladder or step meter beside the grid, showing the rungs still to come'],
			note: 'The ladder should be visible BEFORE it is climbed. A meter that only shows the ' +
				'current value hides the reason to want another cascade.',
		},
		method: (cfg) =>
			py([
				'    def step_cascade_multiplier(self) -> None:',
				`        """Advance the multiplier one rung per cascade: ${cfg.ladder.join(', ')}.`,
				'',
				'        Generated by stake-forge from game.cascadeMultiplier. The ladder is',
				'        per SEQUENCE, not per round — cascade_step is reset at the start of',
				'        every spin, or the multiplier would climb all round and be a',
				'        different mechanic wearing this one\'s name.',
				'',
				'        Holds at the top rung rather than running off the end of the list,',
				'        so a long sequence is rewarded without being unbounded.',
				'',
				'        The FIRST cascade reads ladder[1], not ladder[0]. This fires after',
				'        a tumble, so by then the initial win has already paid at the engine',
				'        default of 1x — which is what ladder[0] describes. Gonzo\'s own',
				'        shape reads as [1, 2, 3, 5] for exactly that reason.',
				'        """',
				'        self.cascade_step = getattr(self, "cascade_step", 0) + 1',
				`        ladder = ${JSON.stringify(cfg.ladder)}`,
				'        index = min(self.cascade_step, len(ladder) - 1)',
				'        self.global_multiplier = ladder[index]',
				'        update_global_mult_event(self)',
			]),
	},

	// ── symbol rewrites ──────────────────────────────────────────────────────
	mysterySymbols: {
		id: 'mystery_symbol',
		name: 'Mystery symbols',
		specKey: 'mysterySymbols',
		winTypes: ['lines', 'ways', 'cluster'],
		boardLifetime: 'this-evaluation',
		seenIn: 'Mystery Museum (Push Gaming)',
		imports: [{ module: 'random', plain: true }],
		site: 'after-draw',
		call: 'self.reveal_mystery_symbols()',
		art: {
			symbols: 'A mystery cover symbol, plus every payable symbol it can reveal as.',
			states: ['reveal'],
			animations: [
				'a SIMULTANEOUS reveal across every mystery cell — one beat, not a stagger; ' +
					'the point is that they are all the same symbol',
			],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def reveal_mystery_symbols(self) -> None:',
				'        """Turn every mystery cell into ONE randomly chosen symbol type.',
				'',
				'        Generated by stake-forge from game.mysterySymbols. The whole tension',
				'        is that they reveal together and identically — revealing them',
				'        independently is a different, much weaker mechanic.',
				'        """',
				`        positions = [`,
				'            (r, y)',
				'            for r, reel in enumerate(self.board)',
				'            for y, sym in enumerate(reel)',
				`            if sym.name == "${cfg.cover}"`,
				'        ]',
				'        if not positions:',
				'            return',
				`        revealed = random.choices(${JSON.stringify(cfg.pool)}, weights=${JSON.stringify(cfg.poolWeights)})[0]`,
				'        for reel, row in positions:',
				'            self.board[reel][row] = self.create_symbol(revealed)',
			]),
	},

	symbolUpgrade: {
		id: 'symbol_upgrade',
		name: 'Symbol upgrade',
		specKey: 'symbolUpgrade',
		winTypes: ['lines', 'ways', 'cluster', 'scatter'],
		boardLifetime: 'this-evaluation',
		seenIn: 'Jack and the Beanstalk (NetEnt)',
		imports: [{ module: 'random', plain: true }],
		site: 'after-draw',
		call: 'self.upgrade_symbols()',
		art: {
			symbols: 'Each low symbol needs a promotion transition into its target.',
			states: ['upgrade'],
			animations: ['an upgrade transition per symbol pair — it must read as a promotion'],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def upgrade_symbols(self) -> None:',
				'        """Promote low-paying symbols to a higher tier.',
				'',
				'        Generated by stake-forge from game.symbolUpgrade.',
				'        """',
				`        if self.gametype == self.config.basegame_type and not ${cfg.inBaseGame ? 'True' : 'False'}:`,
				'            return',
				`        if random.random() > ${cfg.chance}:`,
				'            return',
				`        upgrades = ${JSON.stringify(cfg.map)}`,
				'        for reel in range(self.config.num_reels):',
				'            for row in range(self.config.num_rows[reel]):',
				'                name = self.board[reel][row].name',
				'                if name in upgrades:',
				'                    self.board[reel][row] = self.create_symbol(upgrades[name])',
			]),
	},

	symbolTransform: {
		id: 'symbol_transform',
		name: 'Symbol conversion',
		specKey: 'symbolTransform',
		winTypes: ['cluster', 'scatter', 'lines', 'ways'],
		boardLifetime: 'this-evaluation',
		seenIn: 'Reactoonz (Play’n GO)',
		imports: [{ module: 'random', plain: true }],
		site: 'after-draw',
		call: 'self.transform_symbols()',
		art: {
			symbols: [],
			states: ['transform'],
			animations: [
				'a transform that reads as "these became those", fired simultaneously across the board',
			],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def transform_symbols(self) -> None:',
				'        """Turn every instance of one symbol type into another.',
				'',
				'        Generated by stake-forge from game.symbolTransform. LOWERS volatility',
				'        by manufacturing a win that was not on the board.',
				'        """',
				`        if random.random() > ${cfg.chance}:`,
				'            return',
				`        sources = ${JSON.stringify(cfg.from)}`,
				`        target = "${cfg.to}"`,
				'        source = random.choice(sources)',
				'        for reel in range(self.config.num_reels):',
				'            for row in range(self.config.num_rows[reel]):',
				'                if self.board[reel][row].name == source:',
				'                    self.board[reel][row] = self.create_symbol(target)',
			]),
	},

	wildSpawner: {
		id: 'wild_spawner',
		name: 'Wild spawner',
		specKey: 'wildSpawner',
		winTypes: ['cluster', 'lines', 'ways'],
		boardLifetime: 'this-evaluation',
		seenIn: 'Reactoonz (Play’n GO)',
		imports: [{ module: 'random', plain: true }],
		site: 'after-cascade',
		call: 'self.spawn_wilds_from_trigger()',
		art: {
			symbols: 'The spawner source plus the spawned wild.',
			states: ['spawn'],
			animations: ['spawner fire', 'a burst or projectile to each spawned cell'],
			screens: [],
		},
		method: (cfg) =>
			py([
				'    def spawn_wilds_from_trigger(self) -> None:',
				`        """Fire ${cfg.count} wilds onto the grid once a cascade sequence runs long.`,
				'',
				'        Generated by stake-forge from game.wildSpawner. The trigger is the',
				'        cascade COUNT rather than a symbol, so it rewards a sequence the',
				'        player is already watching build.',
				'        """',
				'        self.spawner_cascades = getattr(self, "spawner_cascades", 0) + 1',
				`        if self.spawner_cascades != ${cfg.afterCascades}:`,
				'            return',
				`        for _ in range(${cfg.count}):`,
				'            reel = random.randrange(self.config.num_reels)',
				'            row = random.randrange(self.config.num_rows[reel])',
				`            self.board[reel][row] = self.create_symbol("${cfg.wild}")`,
			]),
	},

	// ── sticky state ─────────────────────────────────────────────────────────
	stickyMultiplierWilds: {
		id: 'sticky_multiplier_wild',
		name: 'Sticky wilds that grow each spin',
		specKey: 'stickyMultiplierWilds',
		// Wild substitution only. On scatter-pays a wild has nothing to substitute
		// INTO, so the mechanic would generate, run, and do nothing.
		winTypes: ['lines', 'ways', 'cluster'],
		// The whole point is that the cells survive — this is the one mechanic here
		// whose writes must outlive the spin that made them.
		boardLifetime: 'this-round',
		seenIn: 'Scroll Keeper (Stake Engine)',
		imports: [],
		site: 'after-draw',
		call: 'self.carry_sticky_multiplier_wilds()',
		// Per ROUND, not per spin. Putting this in `init` would wipe the stuck
		// cells every spin and the mechanic would silently do nothing.
		roundInit: ['self.sticky_mult_wilds = {}'],
		art: {
			symbols: 'The wild, plus a value badge legible over it at every rung of the ladder.',
			states: ['land', 'stick', 'upgrade'],
			animations: [
				'LAND — a wild arriving and locking, distinct from an ordinary wild landing',
				'UPGRADE — the badge stepping up, once per spin, on every stuck wild at once',
				'CAP — the badge reaching its ceiling and stopping, so the player can tell it has',
			],
			screens: [],
			note:
				'Three or four stuck wilds all upgrading in the same beat is the signature moment ' +
				'of this mechanic, so the upgrade animation has to read when several play at once ' +
				'— not a long solo flourish. The badge must stay legible from the start value to ' +
				'the cap, which can be two digits in a cell also showing the wild art.',
		},
		method: (cfg) =>
			py([
				'    def carry_sticky_multiplier_wilds(self) -> None:',
				`        """Stick wilds for the round and step each one ${cfg.step} per spin, capped at ${cfg.cap}.`,
				'',
				'        Generated by stake-forge from game.stickyMultiplierWilds.',
				'',
				'        Order matters: the wilds already stuck are AGED FIRST, then newly',
				`        landed ones are adopted at ${cfg.start}. Adopting first would give a wild`,
				'        that landed this spin a free step it did not earn.',
				'',
				'        How the value actually pays, which is not what most people assume:',
				'        apply_added_symbol_mult() in src/wins/multiplier_strategy.py SUMS the',
				'        multipliers of the winning positions and ignores any value that is',
				'        not greater than 1. So two stuck wilds worth 3 and 5 on one winning',
				'        line pay 8x, not 15x, and a wild sitting off the winning line pays',
				`        nothing at all. That is why the ladder starts at ${cfg.start} rather than 1.`,
				'',
				'        The value only reaches the client if the wild is listed under the',
				'        "multiplier" key of special_symbols — json_ready_sym() filters symbol',
				'        attributes by that list. The spec loader checks it.',
				'        """',
				'        state = getattr(self, "sticky_mult_wilds", None)',
				'        if state is None:',
				'            state = {}',
				'            self.sticky_mult_wilds = state',
				...(cfg.freeSpinsOnly
					? [
							'        if self.gametype != self.config.freegame_type:',
							'            return',
						]
					: []),
				'',
				'        for key in state:',
				`            state[key] = min(state[key] + ${cfg.step}, ${cfg.cap})`,
				'',
				'        for reel, column in enumerate(self.board):',
				'            for row, symbol in enumerate(column):',
				`                if symbol.name == "${cfg.wild}" and (reel, row) not in state:`,
				`                    state[(reel, row)] = ${cfg.start}`,
				'',
				'        for (reel, row), value in state.items():',
				'            if reel >= len(self.board) or row >= len(self.board[reel]):',
				'                continue',
				`            stuck = self.create_symbol("${cfg.wild}")`,
				'            # locked marks the cell as owned for the rest of the round, so a',
				'            # mechanic that stamps a REGION — a colossal block — places around',
				'            # it rather than punching holes in something already promised.',
				'            stuck.assign_attribute({"multiplier": value, "locked": True})',
				'            self.board[reel][row] = stuck',
			]),
	},
};

export const BOARD_MECHANIC_KEYS = Object.keys(BOARD_MECHANICS);

/** The spec keys under `game:` that switch a board mechanic on. */
export const BOARD_MECHANIC_SPEC_KEYS = BOARD_MECHANIC_KEYS.map((k) => BOARD_MECHANICS[k].specKey);

/** Look one up by the spec key that enables it. */
export function boardMechanicFor(specKey) {
	return Object.values(BOARD_MECHANICS).find((m) => m.specKey === specKey) ?? null;
}
