/**
 * Swap screen components between the studio's spine art and a flat placeholder.
 *
 * ── The constraint this works around ────────────────────────────────────────
 * Background.svelte and BoardFrame.svelte are written against spines: they
 * render <SpineProvider key="foregroundAnimation"> and play named tracks
 * ('idle', 'dust', 'reelhouse_glow_start'). pixi-svelte will not accept a PNG
 * there, so a game with no delivered background does not fall back to nothing —
 * it falls back to whichever sample app it was cloned from, and looks like that
 * game. There is no third state in the SDK.
 *
 * So the component is rewritten, not configured. Which version is on disk is
 * decided by the manifest every time `assets:import` runs, in BOTH directions:
 * deliver a spine and the spine version comes back. That matters because a
 * one-way strip would mean the tool could never render real background art
 * again once it had swapped in a placeholder.
 *
 * ── Why the whole file is replaced rather than edited ───────────────────────
 * A regex patch over Svelte markup has to match imports, a reactive $derived,
 * two FadeContainers and their nested tracks, and it silently half-applies when
 * the SDK moves any of it. Writing the file outright is verifiable: the
 * generated version either compiles or it does not, and the spine version is
 * kept verbatim as a sibling so restoring it is a copy, not a reconstruction.
 *
 * The original is stashed on first swap. Nothing else reads the stash, so a
 * missing one means "never swapped" rather than "corrupt".
 */

import fs from 'fs-extra';
import path from 'node:path';

/** Where the untouched spine version is kept while a placeholder is in place. */
const STASH_DIR = '.forge-original';

/** Asset keys the generated components reference. */
export const SCREEN_PLACEHOLDER_KEYS = {
	basegame: 'placeholderBackdropBase',
	freegame: 'placeholderBackdropFeature',
	boardFrame: 'placeholderBoardFrame',
};

function stashPath(appDir, file) {
	return path.join(appDir, 'src', 'components', STASH_DIR, file);
}

function componentPath(appDir, file) {
	return path.join(appDir, 'src', 'components', file);
}

/**
 * Keep the pristine spine version once, so the swap is reversible.
 *
 * Only the FIRST call stashes. A second would overwrite the original with a
 * generated placeholder and make the swap permanent — the exact failure this
 * whole mechanism exists to avoid.
 */
function stashOriginal(appDir, file) {
	const stash = stashPath(appDir, file);
	if (fs.existsSync(stash)) return false;
	const source = componentPath(appDir, file);
	if (!fs.existsSync(source)) return false;
	fs.ensureDirSync(path.dirname(stash));
	fs.copySync(source, stash);
	return true;
}

/** Put the studio's spine version back. Returns false when nothing was stashed. */
function restoreOriginal(appDir, file) {
	const stash = stashPath(appDir, file);
	if (!fs.existsSync(stash)) return false;
	fs.copySync(stash, componentPath(appDir, file));
	fs.removeSync(stash);
	return true;
}

/** Background.svelte, drawn from two flat sprites instead of two spines. */
function backdropComponent() {
	return `<script lang="ts">
	// GENERATED by stake-forge — placeholder backdrop.
	//
	// The spine version of this file is stashed in components/${STASH_DIR}/ and is
	// restored automatically by \`forge assets:import\` as soon as the manifest
	// supplies background.basegame / background.freegame. Do not edit this file;
	// edit the art, or the generator.
	import { Rectangle, Sprite } from 'pixi-svelte';
	import { FadeContainer } from 'components-pixi';
	import { SECOND } from 'constants-shared/time';

	import { getContext } from '../game/context';

	const context = getContext();
	const backgroundProps = $derived(
		context.stateLayoutDerived.normalBackgroundLayout({ scale: 0.5 }),
	);
	const showBaseBackground = $derived(context.stateGame.gameType === 'basegame');
	const showFeatureBackground = $derived(context.stateGame.gameType === 'freegame');
</script>

<Rectangle {...context.stateLayoutDerived.canvasSizes()} backgroundColor={0x0d0f15} zIndex={-3} />

<FadeContainer show={showBaseBackground} duration={SECOND} zIndex={-2}>
	<Sprite key="${SCREEN_PLACEHOLDER_KEYS.basegame}" {...backgroundProps} />
</FadeContainer>

<FadeContainer show={showFeatureBackground} duration={SECOND} zIndex={-1}>
	<Sprite key="${SCREEN_PLACEHOLDER_KEYS.freegame}" {...backgroundProps} />
</FadeContainer>
`;
}

/**
 * BoardFrame.svelte, drawn from one flat sprite.
 *
 * The spine version also carries a glow driven by boardFrameGlowShow/Hide. The
 * glow art is the sample's `reelhouse` spine, so keeping it would keep exactly
 * the art this swap exists to remove. The emitter subscription is kept and made
 * a no-op instead of deleted: dropping it would make the event handler in
 * bookEventHandlerMap.ts broadcast to nothing, which throws at runtime rather
 * than degrading.
 */
function boardFrameComponent() {
	return `<script lang="ts" module>
	export type EmitterEventBoardFrame =
		| { type: 'boardFrameGlowShow' }
		| { type: 'boardFrameGlowHide' };
</script>

<script lang="ts">
	// GENERATED by stake-forge — placeholder board frame.
	//
	// The spine version of this file is stashed in components/${STASH_DIR}/ and is
	// restored by \`forge assets:import\` once the manifest supplies boardFrame.
	import { Sprite } from 'pixi-svelte';

	import { getContext } from '../game/context';

	const context = getContext();

	// The glow is the sample's reelhouse spine, so there is nothing to play here.
	// The subscription stays so the boardFrameGlow* broadcasts still have a
	// listener — removing it makes the book-event handler throw.
	context.eventEmitter.subscribeOnMount({
		boardFrameGlowShow: () => {},
		boardFrameGlowHide: () => {},
	});
</script>

<Sprite
	key="${SCREEN_PLACEHOLDER_KEYS.boardFrame}"
	zIndex={-1}
	anchor={0.5}
	x={context.stateGameDerived.boardLayout().x}
	y={context.stateGameDerived.boardLayout().y}
	width={context.stateGameDerived.boardLayout().width * 1.08}
	height={context.stateGameDerived.boardLayout().height * 1.16}
/>
`;
}

const SWAPS = [
	{
		file: 'Background.svelte',
		// Both slots feed one component, so it takes the placeholder unless BOTH
		// backgrounds are delivered — a half-placeholder background would render
		// the sample's mine for the base game and ours for the feature.
		slots: ['background.basegame', 'background.freegame'],
		render: backdropComponent,
	},
	{
		file: 'BoardFrame.svelte',
		slots: ['boardFrame'],
		render: boardFrameComponent,
	},
];

/**
 * Bring every screen component into line with what the manifest supplies.
 *
 * @param {string} appDir
 * @param {object} manifest  the parsed assets-manifest.yaml
 * @returns {{swapped: string[], restored: string[]}}
 */
export function patchScreenComponents(appDir, manifest) {
	const supplied = manifest?.screens ?? {};
	const swapped = [];
	const restored = [];

	for (const { file, slots, render } of SWAPS) {
		const target = componentPath(appDir, file);
		if (!fs.existsSync(target) && !fs.existsSync(stashPath(appDir, file))) continue;

		const delivered = slots.every((slot) => supplied[slot]);
		if (delivered) {
			if (restoreOriginal(appDir, file)) restored.push(file);
			continue;
		}

		// Already a placeholder — the stash exists and the file is generated. Do
		// not rewrite it, so a re-run is a no-op rather than a spurious diff.
		const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
		if (current.includes('GENERATED by stake-forge — placeholder')) continue;

		stashOriginal(appDir, file);
		fs.writeFileSync(target, render(), 'utf8');
		swapped.push(file);
	}

	return { swapped, restored };
}
