/**
 * Win-level bands — which celebration a round earns.
 *
 * The SDK ships one fixed table, and it is anchored to its own default 5,000x
 * wincap: levels 6-9 sit at 15x/30x/50x/100x and level 10 is the cap exactly.
 * Raise maxWin and the top of that ladder stops working. Measured on a 20,000x
 * game over 400,000 weighted rounds:
 *
 *   level 9 spans 100x-20,000x   278 rounds, from 100x to 6,062x
 *   level 10 is the cap exactly  never fires outside a 1-in-20,000,000 round
 *
 * So every win from 100x upward — including the best thing that realistically
 * happens — gets the SAME celebration, and the top one is unreachable. The
 * escalation flattens exactly where it should peak.
 *
 * Two kinds of threshold, split on what the number MEANS:
 *
 *   levels 1-5   ABSOLUTE, and stay absolute. "Did I get my stake back" is a
 *                question about the stake, not about the cap: 0.1x, 1x, 2x, 5x
 *                mean the same thing in a 1,000x game and a 100,000x game.
 *   levels 6-10  SCALED to maxWin. These are the banners, and what counts as a
 *                big win is relative to what the game can pay.
 *
 * The banner rungs are geometric from the top of the absolute ladder to a
 * fraction of the cap, which keeps them strictly ascending for any cap — a
 * non-ascending table is a live bug, because get_win_level() returns the FIRST
 * band that matches.
 */

/** Where the absolute ladder ends and the banners begin. */
export const BANNER_FLOOR = 15;

/**
 * The top banner sits at a quarter of max win rather than at the cap. At the cap
 * exactly it fires only on a max-win round — 1-in-20,000,000 — which is a
 * celebration no player will ever see. A quarter is still unmistakably huge.
 */
export const TOP_BANNER_FRACTION = 0.25;

/** Levels 1-5: absolute, about the stake. */
export const ABSOLUTE_EDGES = [0, 0.1, 1, 2, 5];

/**
 * The five banner thresholds for a given cap, geometric and strictly ascending.
 *
 * @param {number} maxWin the game's cap, in multiples of the bet
 * @returns {number[]} thresholds for levels 6, 7, 8, 9, 10
 */
export function bannerThresholds(maxWin, floor = BANNER_FLOOR) {
	const top = Math.max(maxWin * TOP_BANNER_FRACTION, floor * 2);
	const ratio = (top / floor) ** (1 / 4);
	const out = [];
	for (let k = 0; k < 5; k += 1) {
		const raw = floor * ratio ** k;
		// Round for readability, then force ascent: two rungs that round to the
		// same number would make one of them dead.
		const value = raw >= 100 ? Math.round(raw / 10) * 10 : Math.round(raw * 10) / 10;
		out.push(out.length && value <= out[out.length - 1] ? out[out.length - 1] + 1 : value);
	}
	return out;
}

/**
 * The full 1..10 edge list for a cap: absolute rungs, then scaled banners.
 * Returned as [lo, hi] pairs so it can be rendered straight into Python.
 */
export function winLevelBands(maxWin, { floor = BANNER_FLOOR, scale = 1 } = {}) {
	const edges = [
		...ABSOLUTE_EDGES.map((e) => e * scale),
		...bannerThresholds(maxWin, floor),
	];
	const bands = [];
	for (let i = 0; i < 10; i += 1) {
		bands.push([edges[i], i === 9 ? null : edges[i + 1]]);
	}
	return bands;
}

/**
 * The end-of-feature ladder: the same shape, measuring a whole free-spin round
 * rather than one spin, so the stake-relative rungs start four times higher.
 * A round that returns your stake is not the same event as a spin that does.
 */
export function featureWinLevelBands(maxWin) {
	// A whole free-spin round is not one spin: on a measured 20,000x game the
	// base-game median round pays 0x while the bought-feature median pays ~30x.
	// So the whole ladder starts higher — the stake-relative rungs by 4x, and the
	// banners from a floor four times the spin floor. The SDK's own two tables
	// carry the same distinction (15/30/50/100 against 50/100/500/2000); losing it
	// would tell an artist that "super win" means one amount when it means two.
	return winLevelBands(maxWin, { floor: BANNER_FLOOR * 4, scale: 4 });
}

/** The generated override, as Python. `null` upper bound becomes infinity. */
export function renderWinLevelOverride(maxWin) {
	const render = (bands) =>
		bands
			.map(
				([lo, hi], i) =>
					`                ${i + 1}: (${lo}, ${hi === null ? 'float("inf")' : hi}),`,
			)
			.join('\n');

	// The end-of-feature ladder measures a whole free-spin round rather than one
	// spin, so it starts where a feature stops being disappointing and is scaled
	// the same way from there.
	const feature = featureWinLevelBands(maxWin);

	return `    def get_win_level(self, win_amount: float, winlevel_key: str) -> int:
        """Which celebration a win earns. GENERATED by stake-forge.

        Overrides the SDK's fixed table, which is anchored to its own default
        5,000x wincap: at maxWin ${maxWin}x its level 9 would span ${ABSOLUTE_EDGES.length * 20}x to ${maxWin}x and its
        level 10 would need an exact max-win round, so every big win would get
        the same banner and the top one would never play.

        Levels 1-5 stay absolute — "did I get my stake back" is about the stake.
        Levels 6-10 scale with max win, geometrically, strictly ascending.
        """
        if winlevel_key == "standard":
            levels = {
${render(winLevelBands(maxWin))}
            }
        elif winlevel_key == "endFeature":
            levels = {
${render(feature)}
            }
        else:
            return super().get_win_level(win_amount, winlevel_key)

        for idx, pair in levels.items():
            if win_amount >= pair[0] and win_amount < pair[1]:
                return idx
        return len(levels)
`;
}

/**
 * ── Why the bands are NOT fitted to the measured distribution ────────────────
 *
 * The obvious next step is to place each banner at a percentile of the game's
 * own winning rounds, so every tier fires at a designed rate whatever shape the
 * game has. It was built and measured, and it is worse. On the 20,000x game:
 *
 *   fitted   level 6 15x-19.4x  1 in 355   <- rarer than level 7
 *            level 7 19.4x-100x 1 in 150
 *            level 9, 10                   never
 *   shipped  level 6 15x-64x    1 in 109
 *            level 7 64x-270x   1 in 296
 *            level 10 5000x+    1 in 200,000
 *
 * Percentile-fitting puts levels 6-8 at 5.7x/21x/72x on this game, which is
 * BELOW the 15x where the absolute rungs stop — so either the banners collide
 * with "did I get my stake back", or clamping them to 15x squashes level 6 into
 * a 4x-wide band that fires less often than the tier above it.
 *
 * The residue this was trying to fix — levels 8 and 9 firing only 1-in-66,667
 * and 1-in-133,333 in base play — is not a ladder problem. It is the game's win
 * distribution: 87% of base wins pay under the stake, p99 is 16x, p99.9 is 150x,
 * and then there is a thin tail to ~6,300x. There is nothing between 270x and
 * the tail to celebrate, and no banding hides that. The stock table hid it by
 * making one band cover everything above 100x, which is why its level 9 fired
 * MORE often than its level 8 — an escalation that got commoner as it climbed.
 *
 * Thickening that middle is a MATHS change, not a presentation one: it means
 * moving RTP out of frequent small wins into rarer large ones, which lowers the
 * hit rate. That is a deliberate volatility decision and belongs in the spec.
 */
