/**
 * "expanding" behavior recipe — code emitters.
 *
 * ── Provenance ───────────────────────────────────────────────────────────────
 * The math half below is ADAPTED FROM, not inspired by, math-sdk
 * games/0_0_expwilds. Line-for-line correspondence:
 *
 *   assign_new_wilds()            <- games/0_0_expwilds/game_executables.py:25-42
 *   update_with_existing_wilds()  <- games/0_0_expwilds/game_executables.py:12-23
 *   assign_mult_property()        <- games/0_0_expwilds/game_override.py:20-26
 *   reset_book() additions        <- games/0_0_expwilds/game_override.py:11-15
 *   new_expanding_wild_event()    <- games/0_0_expwilds/game_events.py:14-22
 *   update_expanding_wild_event() <- games/0_0_expwilds/game_events.py:25-36
 *   run_freespin() call order     <- games/0_0_expwilds/gamestate.py:39-68
 *
 * The only intentional changes are (a) the wild symbol name is parameterised
 * from the spec instead of being hardcoded "W", and (b) the `row: 0` that
 * 0_0_expwilds writes when recording an expanded wild is preserved verbatim,
 * because the event emitter adds the padding offset itself.
 *
 * Verified by running games/0_0_expwilds: GameConfig() instantiates, and
 * GameState.run_spin() under criteria="freegame" emitted newExpandingWilds with
 * payload [{reel, row, mult}] and 10 updateExpandingWilds across the round.
 *
 * The web half has NO sample to copy — web-sdk ships no expanding-wild app — so
 * it follows the "Steps to Add a New BookEvent" procedure in web-sdk/README.md,
 * modelled on the shipped GlobalMultiplier.svelte / FreeSpinCounter.svelte
 * components for the emitterEvent + subscribeOnMount shape.
 */

/**
 * @param {object} ctx
 * @param {string} ctx.wildSymbol      the spec symbol carrying the behavior
 * @param {string} ctx.gameName
 * @param {string[]} ctx.gameTypes
 */
export function renderExpandingMath({ wildSymbol }) {
	const W = wildSymbol;

	// Appended to the sample game's EXISTING GameExecutables class rather than
	// replacing game_executables.py. That file carries the mechanic's own win
	// evaluator (evaluate_lines_board on lines, get_clusters_update_wins on
	// cluster, ...) which gamestate.py calls — overwriting it breaks the game.
	const executableMethods = `    def update_with_existing_wilds(self) -> None:
        """Overwrite the freshly drawn board with the wilds that are already stuck.

        Each existing wild re-rolls its multiplier on every reveal: the wild is
        sticky, the multiplier on it is not. Adapted from 0_0_expwilds.
        """
        for expwild in self.expanding_wilds:
            new_mult_on_reveal = get_random_outcome(
                self.get_current_distribution_conditions()["mult_values"][self.gametype]
            )
            expwild["mult"] = new_mult_on_reveal
            for row, _ in enumerate(self.board[expwild["reel"]]):
                self.board[expwild["reel"]][row] = self.create_symbol(EXPANDING_WILD_SYMBOL)
                self.board[expwild["reel"]][row].assign_attribute({"multiplier": new_mult_on_reveal})

    def assign_new_wilds(self, max_num_new_wilds: int) -> None:
        """Land up to max_num_new_wilds new wilds, one per not-yet-used reel."""
        self.new_exp_wilds = []
        for _ in range(max_num_new_wilds):
            if len(self.avaliable_reels) > 0:
                chosen_reel = random.choice(self.avaliable_reels)
                chosen_row = random.choice([i for i in range(self.config.num_rows[chosen_reel])])
                self.avaliable_reels.remove(chosen_reel)

                wr_mult = get_random_outcome(
                    self.get_current_distribution_conditions()["mult_values"][self.gametype]
                )
                expwild_details = {"reel": chosen_reel, "row": chosen_row, "mult": wr_mult}
                self.board[expwild_details["reel"]][expwild_details["row"]] = self.create_symbol(
                    EXPANDING_WILD_SYMBOL
                )
                self.board[expwild_details["reel"]][expwild_details["row"]].assign_attribute(
                    {"multiplier": wr_mult}
                )
                self.new_exp_wilds.append(expwild_details)
`;

	const events = `"""Book events for the expanding-wild feature.

Adapted from math-sdk games/0_0_expwilds/game_events.py. GENERATED by stake-forge.

Both events carry rows already offset for board padding, because the client
renders a board padded by one row top and bottom when config.include_padding is
True. This mirrors 0_0_expwilds exactly — do not offset again on the client.
"""

from copy import deepcopy

NEW_EXP_WILDS = "newExpandingWilds"
UPDATE_EXP_WILDS = "updateExpandingWilds"


def new_expanding_wild_event(gamestate) -> None:
    """Emit the wilds that landed on THIS reveal. Passed after the reveal event."""
    new_exp_wilds = deepcopy(gamestate.new_exp_wilds)
    if gamestate.config.include_padding:
        for ew in new_exp_wilds:
            ew["row"] += 1

    event = {"index": len(gamestate.book.events), "type": NEW_EXP_WILDS, "newWilds": new_exp_wilds}
    gamestate.book.add_event(event)


def update_expanding_wild_event(gamestate) -> None:
    """Emit the re-rolled multiplier on every already-stuck wild (sent before reveal)."""
    existing_wild_details = deepcopy(gamestate.expanding_wilds)
    wild_event = []
    if gamestate.config.include_padding:
        for ew in existing_wild_details:
            if len(ew) > 0:
                ew["row"] += 1
                wild_event.append(ew)
    else:
        wild_event = existing_wild_details

    event = {
        "index": len(gamestate.book.events),
        "type": UPDATE_EXP_WILDS,
        "existingWilds": wild_event,
    }
    gamestate.book.add_event(event)
`;

	/**
	 * The exact call order 0_0_expwilds uses inside run_freespin(), spliced in
	 * place of the sample's own `self.draw_board(...)` line.
	 *
	 * draw_board is called with emit_event=False so the reveal is emitted AFTER
	 * the wilds have been written onto the board — otherwise the client would
	 * receive a board without them. That ordering is 0_0_expwilds', verbatim.
	 */
	const freespinBlock = [
		'self.draw_board(emit_event=False)',
		'',
		'wild_on_reveal = get_random_outcome(',
		'    self.get_current_distribution_conditions()["landing_wilds"]',
		')',
		'self.assign_new_wilds(wild_on_reveal)',
		'self.update_with_existing_wilds()',
		'',
		'reveal_event(self)',
		'if len(self.expanding_wilds) > 0:',
		'    update_expanding_wild_event(self)',
		'if len(self.new_exp_wilds) > 0:',
		'    new_expanding_wild_event(self)',
		'',
		'for wild in self.new_exp_wilds:',
		'    self.expanding_wilds.append(',
		'        {"reel": wild["reel"], "row": 0, "mult": wild["mult"]}',
		'    )',
		'self.expanding_wilds = sorted(self.expanding_wilds, key=lambda x: x["reel"])',
	];

	return {
		/** Files the recipe creates outright (only ones no sample game owns). */
		/**
		 * Appended to an existing game_events.py rather than replacing it —
		 * 0_0_cluster's defines update_grid_mult_event(), which its gamestate.py
		 * imports.
		 */
		moduleFunctions: [
			{ file: 'game_events.py', source: events, probe: 'new_expanding_wild_event' },
		],

		/** Methods appended to an existing class, never replacing the file. */
		classMethods: [
			{
				file: 'game_executables.py',
				className: 'GameExecutables',
				probe: 'assign_new_wilds',
				source: executableMethods,
				imports: [
					{ module: null, statement: 'import random' },
					{ module: 'src.calculations.statistics', names: ['get_random_outcome'] },
				],
				constants: [`EXPANDING_WILD_SYMBOL = "${W}"`],
			},
		],

		/** Patches into game_override.py. */
		overridePatches: [
			{
				id: 'expanding:reset_book',
				anchor: 'reset_book',
				pythonBody: [
					'        self.expanding_wilds = []',
					'        self.new_exp_wilds = []',
					'        self.avaliable_reels = [i for i in range(self.config.num_reels)]',
				].join('\n'),
			},
			{
				id: 'expanding:special_symbol_functions',
				symbol: W,
				functionName: 'assign_mult_property',
				// The recipe OWNS this method, replacing any the sample ships.
				// It emits mult_values nested by gametype, and 0_0_ways' own
				// assign_mult_property reads that key FLAT — leaving the sample's
				// reader in place makes the two disagree at runtime.
				ownMethod: true,
				pythonMethod: `    def assign_mult_property(self, symbol) -> None:
        """Roll a multiplier onto the wild. Freegame only, as in 0_0_expwilds."""
        if self.gametype != self.config.basegame_type:
            multiplier_value = get_random_outcome(
                self.get_current_distribution_conditions()["mult_values"][self.gametype]
            )
            symbol.assign_attribute({"multiplier": multiplier_value})
`,
			},
		],

		/** Splices into gamestate.py's run_freespin, whatever the mechanic. */
		gamestatePatches: [
			{
				id: 'expanding:run_freespin_reset',
				method: 'run_freespin',
				mode: 'prepend',
				body: [
					'self.expanding_wilds = []',
					'self.new_exp_wilds = []',
					'self.avaliable_reels = [i for i in range(self.config.num_reels)]',
				],
			},
			{
				id: 'expanding:run_freespin_wilds',
				method: 'run_freespin',
				mode: 'replace-line',
				lineRe: /^\s*self\.draw_board\(/,
				body: freespinBlock,
			},
		],

		gamestateImports: [
			{ module: 'src.calculations.statistics', names: ['get_random_outcome'] },
			{ module: 'src.events.events', names: ['reveal_event'] },
			{ module: 'game_events', names: ['new_expanding_wild_event', 'update_expanding_wild_event'] },
		],

		/** Distribution conditions the recipe's code reads at runtime. */
		requiredConditions: ['landing_wilds', 'mult_values'],

		/**
		 * This recipe reads mult_values NESTED by gametype, in all three places:
		 * update_with_existing_wilds, assign_new_wilds, and the assign_mult_property
		 * it owns outright. That last one REPLACES the sample's own reader — so on
		 * 0_0_ways, whose reader is the only flat one in the SDK, applying this
		 * recipe leaves no flat reader at all and the config must be emitted
		 * nested. Declaring the shape here is what tells the scaffolder that.
		 */
		multValuesShape: 'nested',
	};
}

/**
 * Web half. Emits the new component plus the exact edits web-sdk/README.md's
 * "Steps to Add a New BookEvent" prescribes, as patch descriptors the caller
 * applies to the scaffolded app.
 */
export function renderExpandingWeb({ wildSymbol }) {
	const component = `<script lang="ts" module>
	// GENERATED by stake-forge — expanding-wild behavior for symbol "${wildSymbol}".
	// Follows the emitterEvent shape used by the shipped GlobalMultiplier.svelte
	// and FreeSpinCounter.svelte components.
	export type ExpandingWild = { reel: number; row: number; mult: number };

	export type EmitterEventExpandingWilds =
		| { type: 'expandingWildsAdd'; wilds: ExpandingWild[] }
		| { type: 'expandingWildsUpdate'; wilds: ExpandingWild[] }
		| { type: 'expandingWildsClear' };
</script>

<script lang="ts">
	import { Container } from 'pixi-svelte';

	import { getContext } from '../game/context';

	const context = getContext();

	let wilds = $state<ExpandingWild[]>([]);

	context.eventEmitter.subscribeOnMount({
		expandingWildsAdd: async (emitterEvent) => {
			// New wilds landed this spin: play expand_in, then hold on expand_loop.
			wilds = [...wilds, ...emitterEvent.wilds];
		},
		expandingWildsUpdate: async (emitterEvent) => {
			// Existing wilds re-rolled their multiplier — refresh the displayed value.
			wilds = wilds.map((wild) => {
				const updated = emitterEvent.wilds.find((item) => item.reel === wild.reel);
				return updated ? { ...wild, mult: updated.mult } : wild;
			});
		},
		expandingWildsClear: () => {
			wilds = [];
		},
	});
</script>

<Container>
	{#each wilds as wild (wild.reel)}
		<!--
			One overlay per expanded reel. Point this at your own spine once
			\`forge assets:import\` has registered it; the audit command checks that
			the manifest supplies expand_in / expand_loop / expand_out for "${wildSymbol}".
		-->
		<Container x={wild.reel} y={wild.row} />
	{/each}
</Container>
`;

	const bookEventTypes = `type BookEventNewExpandingWilds = {
	index: number;
	type: 'newExpandingWilds';
	newWilds: { reel: number; row: number; mult: number }[];
};

type BookEventUpdateExpandingWilds = {
	index: number;
	type: 'updateExpandingWilds';
	existingWilds: { reel: number; row: number; mult: number }[];
};`;

	const handlers = `	newExpandingWilds: async (bookEvent: BookEventOfType<'newExpandingWilds'>) => {
		await eventEmitter.broadcastAsync({ type: 'expandingWildsAdd', wilds: bookEvent.newWilds });
	},
	updateExpandingWilds: async (bookEvent: BookEventOfType<'updateExpandingWilds'>) => {
		await eventEmitter.broadcastAsync({
			type: 'expandingWildsUpdate',
			wilds: bookEvent.existingWilds,
		});
	},`;

	return {
		files: [{ path: 'src/components/ExpandingWilds.svelte', contents: component, mode: 'create' }],
		bookEventTypes,
		bookEventUnionMembers: ['BookEventNewExpandingWilds', 'BookEventUpdateExpandingWilds'],
		handlers,
		emitterImport: {
			typeName: 'EmitterEventExpandingWilds',
			from: '../components/ExpandingWilds.svelte',
		},
		/**
		 * Story fixtures, shaped from the payloads a real 0_0_expwilds run
		 * emitted rather than invented.
		 */
		storyEvents: {
			newExpandingWilds: {
				type: 'newExpandingWilds',
				newWilds: [
					{ reel: 0, row: 4, mult: 2 },
					{ reel: 1, row: 3, mult: 2 },
				],
			},
			updateExpandingWilds: {
				type: 'updateExpandingWilds',
				existingWilds: [
					{ reel: 0, row: 1, mult: 5 },
					{ reel: 1, row: 1, mult: 3 },
				],
			},
		},
	};
}
