import fs from 'fs-extra';
import path from 'node:path';
import chalk from 'chalk';

import { loadGameSpec } from '../lib/loadSpec.js';
import { buildArtBrief } from '../lib/artBrief.js';

/**
 * `forge brief` — what to draw, before any art exists.
 *
 * Three output shapes because three different people need this: Markdown for the
 * art lead, CSV for whatever tracker the work is scheduled in, JSON for anything
 * that wants to consume it programmatically.
 */
export function brief({ specPath, format = 'md', out, quiet = false }) {
	const spec = loadGameSpec(specPath);
	const data = buildArtBrief(spec);

	const rendered =
		format === 'json'
			? JSON.stringify(data, null, 2)
			: format === 'csv'
				? renderCsv(data)
				: format === 'manifest'
					? renderManifest(data)
					: renderMarkdown(data);

	if (out) {
		fs.ensureDirSync(path.dirname(path.resolve(out)));
		fs.writeFileSync(out, rendered, 'utf8');
		if (!quiet) {
			console.log(chalk.green('✓'), `wrote ${out}`);
			printSummary(data);
		}
	} else {
		console.log(rendered);
	}

	return { data, rendered };
}

function printSummary(data) {
	const t = data.totals;
	console.log('');
	console.log(chalk.bold(`  ${data.game.name} — ${data.game.mechanic}, ${data.game.maxWin.toLocaleString('en-US')}x cap`));
	console.log(`  ${t.symbols} symbols x ${t.symbolStates} animation states in total`);
	console.log(`  ${t.requiredScreens} required screen assets (${t.screens} total slots)`);
	console.log(`  ${t.banners} win banners, ${t.bannerAnimations} animations`);
	console.log(
		`  ${t.localisedFrames} localised text frames ` +
			chalk.dim(`(${data.localised.length} sheets x ${data.locales.length} languages)`),
	);
	console.log(`  ${t.sounds} sounds`);
}

const num = (n) =>
	!Number.isFinite(n) ? '∞' : n >= 1000 ? Math.round(n).toLocaleString('en-US') : Math.round(n * 100) / 100;

function renderMarkdown(d) {
	const L = [];
	L.push(`# Art brief — ${d.game.name}\n`);
	L.push(
		`${d.game.mechanic} · ${d.game.reels.count} reels x ${d.game.reels.rows.join('/')} rows · ` +
			`${(d.game.rtp * 100).toFixed(2)}% RTP · ${d.game.volatility} volatility · ` +
			`**${num(d.game.maxWin)}x max win**\n`,
	);
	L.push(
		'Generated by `forge brief` from `game-spec.yaml`. Every requirement below is read from the ' +
			'web-sdk sample apps, not chosen — the engine will look for these keys, at these sizes, ' +
			'with these animation names. What goes inside the frame is yours.\n',
	);

	// ── the headline numbers, first, because that is what gets scheduled ─────
	const t = d.totals;
	L.push('## The size of the job\n');
	L.push('| | Count |');
	L.push('|---|---|');
	L.push(`| Symbols | ${t.symbols} |`);
	L.push(`| Symbol animation states (total across all symbols) | ${t.symbolStates} |`);
	L.push(`| Screen assets required | ${t.requiredScreens} of ${t.screens} slots |`);
	L.push(`| Win banners | ${t.banners} sets, ${t.bannerAnimations} animations |`);
	L.push(`| Localised text frames | **${t.localisedFrames}** (${d.localised.length} sheets x ${d.locales.length} languages) |`);
	L.push(`| Sounds | ${t.sounds} |`);
	L.push('');

	// ── symbols ──────────────────────────────────────────────────────────────
	L.push('## Symbols\n');
	L.push(
		`Each symbol is a **spine skeleton** sharing one \`symbols.atlas\` + \`symbols.png\`, drawn at ` +
			`**${d.symbols[0]?.size.width ?? 200}x${d.symbols[0]?.size.height ?? 200}px**. ` +
			`A \`*_static.webp\` flat image can stand in for the non-animating states, which is cheaper to render.\n`,
	);
	for (const s of d.symbols) {
		L.push(`### ${s.name} — ${s.label}  \`${s.role}\`${s.special.length ? ` · special: ${s.special.join(', ')}` : ''}\n`);
		if (s.note) L.push(`> ${s.note}\n`);
		if (s.behaviours.length) {
			L.push(`Behaviours: ${s.behaviours.map((b) => `**${b.title}**`).join(', ')}\n`);
		}
		L.push('| State | Animation name | Required by |');
		L.push('|---|---|---|');
		for (const st of s.states) {
			L.push(`| \`${st.state}\` | \`${st.animationName}\` | ${st.requiredBy.join(', ')} |`);
		}
		L.push(`| _static fallback_ | \`${s.staticSprite}\` | optional, cheaper to render |`);
		L.push('');
	}

	// ── screens ──────────────────────────────────────────────────────────────
	L.push('## Screens and board furniture\n');
	L.push('| Slot | Asset key | Type | Animations | Required | Reusable | Drives |');
	L.push('|---|---|---|---|---|---|---|');
	for (const s of d.screens) {
		L.push(
			`| ${s.id} | \`${s.assetKey}\` | ${s.assetType} | ${s.animations.map((a) => `\`${a}\``).join(', ') || '—'} | ` +
				`${s.required ? '**yes**' : 'no'} | ${s.reusableAcrossGames ? 'across games' : 'per game'} | ${s.component} |`,
		);
	}
	L.push('');
	L.push('_"Reusable across games" means this asset is identical in every title we ship — draw it once._\n');

	// ── banners ──────────────────────────────────────────────────────────────
	L.push('## Win banners\n');
	L.push(
		'Only levels 6-10 render a banner; levels 1-5 are count-ups with no art. ' +
			'**The same banner plays on two different scales**: `standard` for a single win during a ' +
			'spin, `endFeature` for the total of a whole free-spin round. Level 7 means 30x-50x in one ' +
			'and 100x-500x in the other, so pitch the animation to cover both.\n',
	);
	L.push(
		`The bands are fixed multiples of the bet — they do NOT slide with the cap. Only level 9's ` +
			`ceiling and level 10's floor track this game's ${num(d.game.maxWin)}x max win.\n`,
	);
	L.push('| Level | Name | Single win | Feature total | Animations |');
	L.push('|---|---|---|---|---|');
	for (const b of d.banners) {
		L.push(
			`| ${b.level} | ${b.alias} | ${num(b.standard.from)}x – ${num(b.standard.to)}x | ` +
				`${num(b.endFeature.from)}x – ${num(b.endFeature.to)}x | ${b.animations.map((a) => `\`${a}\``).join(', ')} |`,
		);
	}
	L.push('');
	const stretched = d.banners.filter((b) => Number.isFinite(b.widestRatio) && b.widestRatio > 100);
	for (const b of stretched) {
		L.push(
			`> **Level ${b.level} (${b.alias}) covers a ${num(b.widestRatio)}x range** — from ` +
				`${num(b.standard.from)}x to ${num(b.standard.to)}x. That is one banner behind wins that ` +
				`feel nothing alike. Worth designing it to escalate with the count-up rather than ` +
				`playing flat.\n`,
		);
	}

	// ── localisation ─────────────────────────────────────────────────────────
	L.push('## Localised text art\n');
	L.push(
		'**This is baked artwork, not strings.** The sample apps render these words as images, one ' +
			`per language, so each sheet below needs ${d.locales.length} renderings. It is the most ` +
			'under-estimated line in a slot art budget, which is why it is itemised.\n',
	);
	L.push(`Languages: ${d.locales.map((l) => `\`${l}\``).join(' · ')}\n`);
	L.push('| Sheet | Asset key | Content | Frames |');
	L.push('|---|---|---|---|');
	for (const l of d.localised) {
		L.push(`| \`${l.sheet}\` | \`${l.assetKey}\` | ${l.content} | ${l.count}${l.extraFrames.length ? ` + ${l.extraFrames.length} unlocalised` : ''} |`);
	}
	L.push('');
	L.push(`**Total: ${d.totals.localisedFrames} localised frames.** Nothing else in the sample carries language variants.\n`);

	// ── mechanic extras ──────────────────────────────────────────────────────
	if (d.fromMechanics.animations.length || d.fromMechanics.screens.length) {
		L.push('## What this game\'s mechanics add\n');
		L.push(`Mechanics in play: ${d.fromMechanics.mechanics.map((m) => `\`${m}\``).join(', ')}\n`);
		if (d.fromMechanics.symbols.length) {
			L.push('**Symbol requirements**\n');
			for (const s of d.fromMechanics.symbols) L.push(`- _${s.mechanic}_ — ${s.requirement}`);
			L.push('');
		}
		if (d.fromMechanics.animations.length) {
			L.push('**Animations**\n');
			for (const a of d.fromMechanics.animations) L.push(`- ${a}`);
			L.push('');
		}
		if (d.fromMechanics.screens.length) {
			L.push('**Screens**\n');
			for (const s of d.fromMechanics.screens) L.push(`- ${s}`);
			L.push('');
		}
		if (d.fromMechanics.notes.length) {
			L.push('**Watch out for**\n');
			for (const n of d.fromMechanics.notes) L.push(`- _${n.mechanic}_ — ${n.note}`);
			L.push('');
		}
	}

	// ── sound ────────────────────────────────────────────────────────────────
	L.push('## Sound\n');
	L.push('Named as `forge sound:build` expects them — drop the files in `sounds-source/` and it builds the sprite.\n');
	L.push('| Name | Kind | Loops | Note |');
	L.push('|---|---|---|---|');
	for (const s of d.sounds) {
		L.push(`| \`${s.name}\` | ${s.kind} | ${s.loops ? 'yes' : 'no'} | ${s.note ?? ''} |`);
	}
	L.push('');

	L.push('---\n');
	L.push(
		'When every item above exists, `forge audit --spec game-spec.yaml --manifest assets-manifest.yaml` ' +
			'passes with zero errors. That equivalence is asserted by a test, so this brief cannot ' +
			'quietly drift from the checker.\n',
	);
	return L.join('\n');
}

/** One row per deliverable, for a tracker. */
function renderCsv(d) {
	const rows = [['category', 'item', 'detail', 'format', 'required', 'note']];
	const esc = (v) => {
		const s = String(v ?? '');
		return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
	};

	for (const s of d.symbols) {
		for (const st of s.states) {
			rows.push([
				'symbol',
				`${s.name} — ${s.label}`,
				`${st.state} (${st.animationName})`,
				`spine ${s.size.width}x${s.size.height}`,
				'yes',
				st.requiredBy.join('; '),
			]);
		}
		rows.push(['symbol', `${s.name} — ${s.label}`, 'static fallback', s.staticSprite, 'no', s.note ?? '']);
	}
	for (const s of d.screens) {
		rows.push([
			'screen',
			s.id,
			s.animations.join('; ') || '—',
			`${s.assetType} (${s.assetKey})`,
			s.required ? 'yes' : 'no',
			`${s.reusableAcrossGames ? 'REUSABLE across games. ' : ''}${s.note ?? ''}`,
		]);
	}
	for (const b of d.banners) {
		rows.push([
			'banner',
			`level ${b.level} — ${b.alias}`,
			b.animations.join('; '),
			'spine',
			'yes',
			`fires from ${num(b.from)}x to ${num(b.to)}x`,
		]);
	}
	for (const l of d.localised) {
		for (const frame of l.frames) {
			rows.push(['localised text', l.assetKey, frame, 'sprite frame', 'yes', l.content]);
		}
	}
	for (const s of d.sounds) {
		rows.push(['sound', s.name, s.kind, s.loops ? 'looping' : 'one-shot', 'yes', s.note ?? '']);
	}
	return rows.map((r) => r.map(esc).join(',')).join('\n') + '\n';
}


/**
 * The brief as an assets-manifest.yaml skeleton.
 *
 * This is what closes the loop. The brief says what to draw; this says where to
 * put it, in exactly the shape `forge audit` reads — so the art team fills in
 * filenames rather than learning a manifest format, and the moment every file
 * exists the audit passes.
 *
 * A test asserts that equivalence by generating this, creating the files it
 * names, and running the real audit. Without it the brief and the checker would
 * drift, and a brief that no longer matches what is checked is worse than none.
 */
function renderManifest(d) {
	const L = [];
	L.push('# ─────────────────────────────────────────────────────────────────');
	L.push(`#  assets-manifest.yaml — generated by \`forge brief\` for ${d.game.name}`);
	L.push('#');
	L.push('#  Every state below is REQUIRED. Fill in the animation names as they');
	L.push('#  exist inside your exported skeletons, then:');
	L.push('#');
	L.push('#    forge audit --spec game-spec.yaml --manifest assets-manifest.yaml');
	L.push('#');
	L.push('#  Delete a symbol from spineSymbols and add it to spriteSymbols if it');
	L.push('#  is a flat image rather than a spine export — it renders, it just');
	L.push('#  does not animate.');
	L.push('# ─────────────────────────────────────────────────────────────────');
	L.push('');
	L.push('assetsSourceDir: ./assets-source');
	L.push('');
	L.push('spineSymbols:');
	for (const s of d.symbols) {
		const lower = s.name.toLowerCase();
		L.push(`  ${s.name}:                     # ${s.label} (${s.role})`);
		L.push('    atlas: symbols.atlas');
		L.push('    png: symbols.png');
		L.push(`    skeleton: ${lower}.json`);
		L.push(`    staticSprite: ${s.staticSprite}`);
		L.push('    animations:');
		for (const st of s.states) {
			L.push(`      ${st.state}: ${st.animationName}`.padEnd(46) + `# ${st.requiredBy.join(', ')}`);
		}
		L.push('');
	}
	L.push('# ── Screens ─────────────────────────────────────────────────────');
	L.push('#  Required slots are uncommented. The rest are real slots the engine');
	L.push('#  will use if you supply them — uncomment as the art arrives.');
	L.push('#');
	L.push('#  The FIELDS differ by asset type, and the engine cares: a spine needs');
	L.push('#  atlas + png + skeleton, a sprite sheet needs one json, a flat sprite');
	L.push('#  needs one image. Getting this wrong is a runtime miss, not a build');
	L.push('#  error, so the type is stated on every line.');
	L.push('screens:');
	for (const s of d.screens) {
		const p = s.required ? '  ' : '  # ';
		L.push(`${p}${s.id}:${' '.repeat(Math.max(1, 30 - s.id.length))}# ${s.assetType} · ${s.component}${s.required ? ' · REQUIRED' : ''}`);
		if (s.assetType === 'spine') {
			L.push(`${p}  atlas: ${s.assetKey}.atlas`);
			L.push(`${p}  png: ${s.assetKey}.png`);
			L.push(`${p}  skeleton: ${s.assetKey}.json`);
		} else {
			// sprites / spriteSheet / sprite all resolve to a single file.
			L.push(`${p}  sprite: ${s.assetKey}.json`);
		}
		if (s.animations.length) {
			L.push(`${p}  # animations needed: ${s.animations.join(', ')}`);
		}
	}
	L.push('');
	return L.join('\n') + '\n';
}

export { renderMarkdown, renderCsv, renderManifest };
