import fs from 'fs-extra';
import path from 'node:path';
import YAML from 'yaml';
import chalk from 'chalk';

import { analyseInspiration } from '../lib/inspire.js';
import { getRecipe } from '../lib/behaviorRecipes.js';
import { INSPIRATION_RULES } from '../lib/inspirationRules.js';

/**
 * Turn a plain-language feature checklist into a draft game-spec.yaml plus a
 * report of what is off-the-shelf versus what needs custom code.
 *
 * The analysis itself lives in src/lib/inspire.js so the app and the CLI share
 * one implementation. This command is the file IO and the human-readable report.
 */

export function inspire({ inputPath, outPath, reportPath, force }) {
	const raw = fs.readFileSync(inputPath, 'utf8');
	let input;
	try {
		input = YAML.parse(raw);
	} catch (err) {
		throw new Error(`${path.basename(inputPath)} is not valid YAML: ${err.message}`);
	}

	const features = input?.features ?? input?.mechanics ?? [];
	if (!Array.isArray(features) || !features.length) {
		throw new Error(
			'inspiration.yaml needs a `features:` list of plain-language lines, e.g.\n' +
				'  features:\n' +
				'    - "sticky wilds during free spins"\n' +
				'    - "buy-bonus at 100x"',
		);
	}

	const result = analyseInspiration({
		name: input.name,
		providerName: input.providerName,
		features,
		references: input.references ?? [],
		raw,
	});

	if (fs.existsSync(outPath) && !force) {
		throw new Error(`${path.basename(outPath)} already exists. Re-run with --force to overwrite it.`);
	}

	const header =
		`# DRAFT game-spec.yaml, generated by \`forge inspire\` from a plain-language checklist.\n` +
		`#\n` +
		`# What is trustworthy here: mechanic, symbol roles, order, special keys and behaviors.\n` +
		`# What is NOT: paytable values, rtp, reel weights and maxWin are placeholders. Nothing\n` +
		`# about payout maths can be derived from a description of mechanics — that comes from a\n` +
		`# math-sdk optimisation run.\n` +
		`#\n` +
		`# Review it, then:  forge audit --spec ${path.basename(outPath)} --manifest assets-manifest.yaml\n\n`;

	fs.writeFileSync(outPath, header + YAML.stringify(result.draft, { lineWidth: 0 }), 'utf8');
	fs.writeFileSync(reportPath, renderReport({ input, result, outPath }), 'utf8');

	// ── console ─────────────────────────────────────────────────────────────
	console.log(chalk.bold(`\nInspiration intake — ${result.lines.length} feature line(s)\n`));
	console.log(
		`  mechanic: ${chalk.bold(result.mechanic)}  ` +
			chalk.dim(`(${result.mechanicProfile.mathSample} / apps/${result.mechanicProfile.webApp})`) +
			'\n',
	);

	for (const line of result.lines) {
		if (!line.rules.length) {
			console.log(`  ${chalk.yellow('?')} ${line.text}`);
			console.log(`      ${chalk.dim('no rule matched — decide this one by hand')}`);
			continue;
		}
		const tag = line.tier === 2 ? chalk.green('T2') : chalk.magenta('T3');
		console.log(`  ${tag} ${line.text}`);
		for (const rule of line.rules) {
			console.log(`      ${chalk.dim(`${rule.implies} — ${rule.reference}`)}`);
		}
	}

	for (const r of result.refused) {
		console.log(
			chalk.yellow(`\n  ! behavior "${r.behavior}" was NOT attached: ${r.reason}, not "${r.mechanic}".`),
		);
	}

	console.log(
		`\n  ${chalk.green('T2')} built-in, config only · ${chalk.magenta('T3')} bespoke, needs a behavior recipe\n` +
			`  ${result.tier3.length} bespoke item(s), ${result.unmatched.length} undecided\n`,
	);
	console.log(chalk.green('✓'), `wrote ${path.basename(outPath)}`);
	console.log(chalk.green('✓'), `wrote ${path.basename(reportPath)}\n`);

	return { ok: true, ...result };
}

function renderReport({ input, result, outPath }) {
	const { lines, mechanic, mechanicProfile: profile, attached, refused, unmatched, notes, extracted, references } = result;
	const out = [];

	out.push(`# Inspiration report — ${input.name ?? 'new game'}`);
	out.push('');
	out.push(
		`Generated by \`forge inspire\` from a plain-language feature checklist. ` +
			`No asset files, source, or client bundle from any other game was read to produce this.`,
	);
	out.push('');
	out.push(`**Mechanic:** \`${mechanic}\` — clone from math \`games/${profile.mathSample}\`, web \`apps/${profile.webApp}\`.`);
	if (references.length) {
		out.push('');
		out.push(`**Drawing from:** ${references.join(', ')} — recorded as a note. No asset, code or bundle from any of them was read.`);
	}
	out.push('');

	const tier2 = [];
	const tier3 = [];
	for (const { text, rules } of lines) {
		for (const rule of rules) {
			(rule.tier === 2 ? tier2 : tier3).push({ text, rule });
		}
	}

	out.push('## Off the shelf (tier 2 — config only)');
	out.push('');
	if (!tier2.length) out.push('_Nothing._');
	else {
		out.push('| Feature | What it maps to | Already wired in |');
		out.push('|---|---|---|');
		for (const { text, rule } of tier2) {
			out.push(`| ${text} | ${rule.implies} | ${rule.reference} |`);
		}
	}
	out.push('');

	out.push('## Needs custom code (tier 3 — bespoke)');
	out.push('');
	if (!tier3.length) out.push('_Nothing._');
	else {
		out.push('| Feature | Behavior tag | Status | Closest reference sample |');
		out.push('|---|---|---|---|');
		for (const { text, rule } of tier3) {
			const recipe = rule.behavior ? getRecipe(rule.behavior) : null;
			const status = recipe
				? recipe.status === 'verified'
					? '**generated** by `forge math:scaffold`'
					: `\`${recipe.status}\` — build by hand`
				: 'no recipe';
			out.push(`| ${text} | ${rule.behavior ? `\`${rule.behavior}\`` : '—'} | ${status} | ${rule.reference} |`);
		}
	}
	out.push('');

	if (attached.length) {
		out.push('## Behaviors attached in the draft');
		out.push('');
		for (const a of attached) out.push(`- \`${a.symbol}\` -> \`behaviors: [${a.behavior}]\``);
		out.push('');
	}

	const ruleNotes = [...new Set(lines.flatMap((l) => l.rules).map((r) => r.note).filter(Boolean))];
	if (ruleNotes.length) {
		out.push('## Things to know before you build these');
		out.push('');
		for (const note of ruleNotes) out.push(`- ${note}`);
		out.push('');
	}

	if (extracted.length) {
		out.push('## Values read out of the checklist');
		out.push('');
		for (const note of extracted) out.push(`- ${note}`);
		out.push('');
	}

	if (refused.length) {
		out.push('## Not attached');
		out.push('');
		for (const r of refused) {
			out.push(`- \`${r.behavior}\` — ${r.reason}, but this spec uses \`${r.mechanic}\`.`);
		}
		out.push('');
	}

	if (unmatched.length) {
		out.push('## Undecided — no rule matched');
		out.push('');
		out.push('These need a human decision. Either reword them using vocabulary the rules know, or');
		out.push('add a rule to `src/lib/inspirationRules.js` — after finding a real sample for it.');
		out.push('');
		for (const text of unmatched) out.push(`- ${text}`);
		out.push('');
		out.push(`Known vocabulary: ${INSPIRATION_RULES.map((r) => `\`${r.id}\``).join(', ')}.`);
		out.push('');
	}

	out.push('## What the draft does NOT contain');
	out.push('');
	out.push('- **Real paytable values.** Placeholders only.');
	out.push('- **Real RTP or reel weights.** These come from a math-sdk optimisation run.');
	out.push('- **Art direction.** Symbol labels are generic; rename them in the draft.');
	out.push('');
	out.push(`Next: review \`${path.basename(outPath)}\`, rename it to \`game-spec.yaml\`, then run \`forge audit\`.`);
	out.push('');

	return out.join('\n');
}
