import fs from 'fs-extra';
import path from 'node:path';
import chalk from 'chalk';

import { loadGameSpec } from '../lib/loadSpec.js';
import { tsStringify } from '../lib/tsSerialize.js';
import { mathGameId } from './mathScaffold.js';

/**
 * Pull the real maths into the web app.
 *
 * Once a simulation has run, the math-sdk holds the authoritative version of
 * two things the tool had only been faking:
 *
 *   config_fe_<game_id>.json  the frontend config — real RTP, real reel strips,
 *                             the paytable as the engine actually built it
 *   books_<mode>.json         simulated rounds, in the exact shape the web-sdk's
 *                             story data files use
 *
 * Until this step exists those two sit in the math-sdk and the web app keeps
 * running on placeholders, which is not just incomplete — it means a paytable
 * edited in the spec but never re-simulated disagrees with the maths silently.
 *
 * ── The one thing that is not a straight copy ────────────────────────────────
 * Game-type keys. The math names its free-game `freegame` (Config.freegame_type),
 * but apps/scatter's config.ts keys its second padding set `freeSpins`, and
 * `GameType = keyof typeof config.paddingReels` derives from those keys. Copying
 * the math's names across verbatim would change the app's type surface. So the
 * mechanic profile stays authoritative for the KEYS, and the math supplies the
 * VALUES, matched by name or by alias.
 */

/** Web game-type key -> the math name that carries its data. */
const GAME_TYPE_ALIASES = {
	freeSpins: 'freegame',
	superspingame: 'superspin',
};

export function mathSync({ specPath, mathSdkDir, sdkDir, dryRun }) {
	const spec = loadGameSpec(specPath);
	const mechanic = spec._mechanic;
	const gameId = mathGameId(spec);

	const library = path.join(mathSdkDir, 'games', gameId, 'library');
	const feConfigPath = path.join(library, 'configs', `config_fe_${gameId}.json`);
	const appDir = path.join(sdkDir, 'apps', spec.game.name);

	if (!fs.existsSync(feConfigPath)) {
		throw new Error(
			`No simulation output at ${path.relative(mathSdkDir, feConfigPath)}.\n` +
				`Run "forge math:run" first — the maths has to exist before it can be synced.`,
		);
	}
	if (!fs.existsSync(appDir)) {
		throw new Error(`apps/${spec.game.name} not found — run "forge scaffold" first.`);
	}

	console.log(chalk.bold(`\nSyncing maths into apps/${spec.game.name}\n`));

	const feConfig = fs.readJsonSync(feConfigPath);
	const { config, notes } = buildConfigFromMath(feConfig, mechanic);

	if (dryRun) {
		console.log(chalk.yellow('Dry run — nothing written.\n'));
		console.log(tsStringify(config).slice(0, 1400));
		return { ok: true, dryRun: true };
	}

	// ── config.ts ───────────────────────────────────────────────────────────
	const header =
		`// GENERATED by stake-forge from the math-sdk's own output.\n` +
		`// Source: games/${gameId}/library/configs/config_fe_${gameId}.json\n` +
		`// This is REAL maths — reel strips, RTP and paytable as the engine built\n` +
		`// them. Re-run \`forge math:run\` and \`forge math:sync\` after changing the\n` +
		`// spec, or this and the maths drift apart.\n`;
	fs.writeFileSync(
		path.join(appDir, 'src', 'game', 'config.ts'),
		`${header}export default ${tsStringify(config)};\n`,
		'utf8',
	);
	console.log(chalk.green('✓'), 'wrote src/game/config.ts from the real maths');
	for (const note of notes) console.log(chalk.cyan('  ·'), note);

	// ── story data ──────────────────────────────────────────────────────────
	const synced = syncBooks({ library, appDir, betModes: Object.keys(spec.game.betModes) });
	for (const s of synced) {
		console.log(
			chalk.green('✓'),
			`src/stories/data/${s.file} — ${s.rounds} real rounds` +
				(s.truncated ? chalk.dim(` (of ${s.total}, capped)`) : ''),
		);
	}
	if (!synced.length) {
		console.log(
			chalk.yellow('  !'),
			'no books found to sync — the simulation may not have produced any',
		);
	}

	console.log(chalk.bold.cyan('\nNext:'));
	console.log(`  forge verify --spec ${path.basename(specPath)} --sdk ${sdkDir}`);
	console.log(chalk.dim('  The preview now plays your own maths, not the sample\'s fixtures.\n'));

	return { ok: true, synced };
}

/**
 * Convert the math's frontend config into the shape config.ts declares.
 *
 * Everything maps across untouched except `symbols`, which the math emits as an
 * array of single-key objects and config.ts declares as an object, and the
 * game-type keys described at the top of this file.
 */
export function buildConfigFromMath(feConfig, mechanic) {
	const notes = [];

	const symbols = {};
	for (const entry of feConfig.symbols ?? []) {
		// [{ H1: {...} }, { L1: {...} }] -> { H1: {...}, L1: {...} }
		for (const [name, value] of Object.entries(entry)) symbols[name] = value;
	}

	const config = {
		providerName: feConfig.providerName,
		gameName: feConfig.gameName,
		gameID: feConfig.gameID,
		rtp: feConfig.rtp,
		numReels: feConfig.numReels,
		numRows: feConfig.numRows,
		betModes: feConfig.betModes,
	};

	if (mechanic.supportsPaylines) {
		if (feConfig.paylines) config.paylines = feConfig.paylines;
		else notes.push('the maths produced no paylines — keeping the key absent');
	} else if (feConfig.paylines) {
		notes.push(`dropped paylines: apps/${mechanic.webApp} has no such key`);
	}

	config.symbols = symbols;
	config.paddingReels = mapPaddingReels(feConfig.paddingReels ?? {}, mechanic, notes);

	return { config, notes };
}

function mapPaddingReels(mathPadding, mechanic, notes) {
	const out = {};

	for (const gameType of mechanic.gameTypes) {
		if (mechanic.paddingReelsStyle === 'empty') {
			// cluster and ways ship empty strings; the maths never sets padding_reels
			// for them, so there is nothing to carry across even if it did.
			out[gameType] = '';
			continue;
		}

		const alias = GAME_TYPE_ALIASES[gameType];
		const value = mathPadding[gameType] ?? (alias ? mathPadding[alias] : undefined);

		if (value === undefined) {
			out[gameType] = '';
			notes.push(
				`no reel strip for "${gameType}"${alias ? ` (or "${alias}")` : ''} — left empty; ` +
					`the key must exist because GameType derives from it`,
			);
			continue;
		}

		out[gameType] = value;
		if (alias && mathPadding[gameType] === undefined) {
			notes.push(`mapped the maths' "${alias}" reel strip onto this app's "${gameType}" key`);
		}
	}

	const unused = Object.keys(mathPadding).filter(
		(k) => !mechanic.gameTypes.includes(k) && !Object.values(GAME_TYPE_ALIASES).includes(k),
	);
	if (unused.length) {
		notes.push(`ignored reel strips the app has no game type for: ${unused.join(', ')}`);
	}

	return out;
}

/**
 * Copy simulated rounds into the story data files.
 *
 * The books are already in the right shape, so this is a re-serialise rather
 * than a conversion. Capped because these files are read by a bundler: a
 * production run is hundreds of thousands of rounds, and storybook only needs
 * enough to pick from.
 */
const MAX_STORY_ROUNDS = 60;

export function syncBooks({ library, appDir, betModes, max = MAX_STORY_ROUNDS }) {
	const dataDir = path.join(appDir, 'src', 'stories', 'data');
	if (!fs.existsSync(dataDir)) return [];

	const synced = [];
	for (const mode of betModes) {
		const bookPath = path.join(library, 'books', `books_${mode}.json`);
		const target = path.join(dataDir, `${mode}_books.ts`);
		// Only replace a story file the sample actually has: writing
		// `superspin_books.ts` into an app with no story referencing it is dead
		// weight the bundler still has to parse.
		if (!fs.existsSync(bookPath) || !fs.existsSync(target)) continue;

		const all = JSON.parse(fs.readFileSync(bookPath, 'utf8'));
		// Prefer rounds that actually pay: a file of 60 zero-win spins makes for a
		// preview where nothing ever happens.
		const winners = all.filter((b) => (b.payoutMultiplier ?? 0) > 0);
		const losers = all.filter((b) => (b.payoutMultiplier ?? 0) === 0);
		const chosen = [...winners.slice(0, Math.ceil(max * 0.7)), ...losers.slice(0, Math.floor(max * 0.3))]
			.slice(0, max)
			.sort((a, b) => a.id - b.id);

		const header =
			`// GENERATED by stake-forge from the math-sdk's own simulation output.\n` +
			`// Source: library/books/books_${mode}.json (${chosen.length} of ${all.length} rounds)\n` +
			`// These are real rounds your maths produced — the preview plays these.\n`;
		fs.writeFileSync(target, `${header}export default ${tsStringify(chosen)};\n`, 'utf8');

		synced.push({
			mode,
			file: `${mode}_books.ts`,
			rounds: chosen.length,
			total: all.length,
			truncated: chosen.length < all.length,
		});
	}
	return synced;
}
