import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderMechanicsDoc } from '../lib/mechanicsDoc.js';

import {
	MECHANIC_LIBRARY,
	getMechanicEntry,
	libraryStats,
	mechanicsForVolatility,
	mechanicsForWinType,
	searchMechanics,
	checkCombination,
	artRequirementsFor,
	STATUS_ORDER,
} from '../lib/mechanicsLibrary.js';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

import { REFERENCE_GAMES, STAKE_ENGINE_STUDIOS, gamesByMaxWin, searchGames } from '../lib/referenceGames.js';

/**
 * `forge mechanics` — browse the researched library.
 *
 * The research used to live in a markdown file nothing could read. This is the
 * same knowledge as a query surface: what works on a cluster board, what reaches
 * 50,000x, who has shipped it, what it costs the art team, and what it conflicts
 * with.
 */

const STATUS_STYLE = {
	built: (s) => chalk.green(s),
	config: (s) => chalk.green(s),
	sample: (s) => chalk.cyan(s),
	roadmap: (s) => chalk.yellow(s),
	blocked: (s) => chalk.red(s),
};

const badge = (status) => (STATUS_STYLE[status] ?? chalk.dim)(status.padEnd(7));

export function mechanics({
	id,
	winType,
	volatility,
	search,
	games,
	maxWin,
	combine,
	art,
	json,
	doc,
	docPath,
} = {}) {
	// Regenerate docs/mechanics-library.md. The doc used to CLAIM it was generated
	// from this library while actually being hand-written, and it drifted: it
	// advertised 54 mechanics against a library holding 56. Now the claim is true
	// and a test fails if the committed file falls behind.
	if (doc) {
		const target = docPath ?? path.join(__dirname, '..', '..', 'docs', 'mechanics-library.md');
		const rendered = renderMechanicsDoc();
		const before = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
		fs.writeFileSync(target, rendered, 'utf8');
		const stats = libraryStats();
		console.log(
			before === rendered
				? chalk.dim(`docs/mechanics-library.md already up to date (${stats.total} mechanics).`)
				: chalk.green('✓') + ` wrote docs/mechanics-library.md — ${stats.total} mechanics, ` +
					`${stats.usableToday} usable today, ${stats.referenceGames} reference games`,
		);
		return { ok: true };
	}

	// ── one mechanic in full ─────────────────────────────────────────────────
	if (id) return showMechanic(id, { json });

	// ── check a proposed combination ─────────────────────────────────────────
	if (combine) {
		const ids = combine.split(',').map((s) => s.trim()).filter(Boolean);
		const result = checkCombination(ids);
		if (json) {
			console.log(JSON.stringify({ ids, ...result, art: artRequirementsFor(ids) }, null, 2));
			return result;
		}
		console.log(chalk.bold(`\nCombination: ${ids.join(' + ')}\n`));
		if (result.unknown.length) {
			console.log(chalk.red(`  Unknown mechanic ids: ${result.unknown.join(', ')}`));
		}
		for (const c of result.conflicts) {
			console.log(chalk.red(`  ✗ ${c.a} + ${c.b}`));
			console.log(chalk.dim(`     ${c.why}`));
		}
		if (result.blocked.length) {
			console.log(chalk.red(`  ✗ blocked: ${result.blocked.join(', ')}`));
			for (const b of result.blocked) {
				console.log(chalk.dim(`     ${MECHANIC_LIBRARY[b].math.notes}`));
			}
		}
		if (!result.conflicts.length && !result.blocked.length && !result.unknown.length) {
			console.log(chalk.green('  ✓ no known conflicts'));
		}
		if (result.notBuilt.length) {
			console.log(
				chalk.yellow(`\n  Not generated by the tool today: ${result.notBuilt.join(', ')}`),
			);
			console.log(chalk.dim('  These are plans. Picking them means building them.'));
		}
		printArt(artRequirementsFor(ids));
		if (result.unknown.length || result.conflicts.length || result.blocked.length) {
			process.exitCode = 1;
		}
		return result;
	}

	// ── the art brief for a set of mechanics ─────────────────────────────────
	if (art) {
		const ids = art.split(',').map((s) => s.trim()).filter(Boolean);
		const requirements = artRequirementsFor(ids);
		if (json) {
			console.log(JSON.stringify(requirements, null, 2));
			return requirements;
		}
		console.log(chalk.bold(`\nArt required for: ${ids.join(' + ')}`));
		printArt(requirements);
		return requirements;
	}

	// ── reference games ──────────────────────────────────────────────────────
	if (games !== undefined) {
		const list = maxWin
			? gamesByMaxWin(Number(maxWin))
			: typeof games === 'string' && games
				? searchGames(games)
				: Object.values(REFERENCE_GAMES);
		if (json) {
			console.log(JSON.stringify(list, null, 2));
			return list;
		}
		console.log(chalk.bold(`\nReference games (${list.length})\n`));
		for (const g of list) {
			console.log(
				`${chalk.bold(g.title.padEnd(30))} ${chalk.dim(g.studio.padEnd(24))} ` +
					`${g.winType.padEnd(8)} ${g.maxWin ? `${g.maxWin.toLocaleString('en-US')}x`.padStart(9) : '        ?'} ${chalk.dim(g.volatility)}`,
			);
			console.log(chalk.dim(`  ${g.mechanics.join(', ')}`));
			console.log(`  ${g.whyItMatters}`);
			console.log('');
		}
		console.log(chalk.bold('Studios shipping on Stake Engine itself:'));
		for (const s of STAKE_ENGINE_STUDIOS) {
			console.log(
				`  ${s.studio.padEnd(24)} ${chalk.dim(s.notableTitles.join(', ') || '—')}`,
			);
		}
		printSourcing();
		return list;
	}

	// ── filtered or full listing ─────────────────────────────────────────────
	let list = Object.values(MECHANIC_LIBRARY);
	if (winType) list = mechanicsForWinType(winType);
	if (volatility) list = list.filter((m) => m.volatility.includes(volatility));
	if (search) {
		const found = new Set(searchMechanics(search).map((m) => m.id));
		list = list.filter((m) => found.has(m.id));
	}

	if (json) {
		console.log(JSON.stringify(list, null, 2));
		return list;
	}

	const stats = libraryStats();
	console.log(chalk.bold(`\nMechanics library — ${list.length} shown of ${stats.total}\n`));

	const byFamily = {};
	for (const m of list) (byFamily[m.family] ??= []).push(m);

	for (const [family, entries] of Object.entries(byFamily)) {
		console.log(chalk.bold.cyan(`  ${family}`));
		for (const m of entries.sort(
			(a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status),
		)) {
			const tm = m.trademark ? chalk.red(' ™') : '';
			console.log(`    ${badge(m.status)} ${chalk.bold(m.id.padEnd(30))}${m.name}${tm}`);
		}
		console.log('');
	}

	console.log(
		chalk.dim('  status: ') +
			chalk.green('built/config') +
			chalk.dim(' = works today · ') +
			chalk.cyan('sample') +
			chalk.dim(' = adaptable from a math-sdk sample · ') +
			chalk.yellow('roadmap') +
			chalk.dim(' = would be built · ') +
			chalk.red('blocked') +
			chalk.dim(' = engine limit or licence'),
	);
	console.log(
		chalk.bold(
			`\n  ${stats.usableToday} of ${stats.total} are usable today. ` +
				`${stats.byStatus.sample} adaptable from samples, ${stats.byStatus.roadmap} would be built, ` +
				`${stats.byStatus.blocked} blocked.`,
		),
	);
	console.log(chalk.dim(`  ${stats.referenceGames} reference games indexed.`));
	console.log(chalk.dim('\n  forge mechanics --id <id>              one mechanic in full'));
	console.log(chalk.dim('  forge mechanics --combine a,b,c        check a combination for conflicts'));
	console.log(chalk.dim('  forge mechanics --art a,b,c            what the art team must produce'));
	console.log(chalk.dim('  forge mechanics --games                the reference game index'));
	printSourcing();
	return list;
}

function showMechanic(id, { json }) {
	const m = getMechanicEntry(id);
	if (!m) {
		console.error(chalk.red(`Unknown mechanic "${id}".`));
		console.error(chalk.dim('Run `forge mechanics` to list them.'));
		process.exitCode = 1;
		return null;
	}
	if (json) {
		console.log(JSON.stringify(m, null, 2));
		return m;
	}

	console.log(chalk.bold(`\n${m.name}  ${badge(m.status)}`));
	console.log(chalk.dim(`${m.family} · ${m.difficulty} · ${m.winTypes.join('/') || 'n/a'} · ${m.volatility.join('/') || 'n/a'} volatility\n`));
	console.log(`  ${m.rule}\n`);

	if (m.note) console.log(chalk.cyan(`  ${m.note}\n`));

	if (m.trademark) {
		console.log(chalk.red.bold('  Trademark / patent'));
		console.log(`    ${m.trademark.name} — ${m.trademark.owner}`);
		console.log(chalk.dim(`    ${m.trademark.note}`));
		console.log(chalk.dim('    Trademarks bite on names and presentation. This is not legal advice.\n'));
	}

	if (m.seenIn.length) {
		console.log(chalk.bold('  Seen in'));
		for (const g of m.seenIn) {
			console.log(`    ${g.title.padEnd(30)} ${chalk.dim(g.studio)}${g.maxWin ? chalk.dim(`  ${g.maxWin.toLocaleString('en-US')}x`) : ''}`);
		}
		console.log('');
	}

	console.log(chalk.bold('  Art required'));
	if (typeof m.art.symbols === 'string' && m.art.symbols) console.log(`    symbols     ${m.art.symbols}`);
	if (m.art.states?.length) console.log(`    states      ${m.art.states.join(', ')}`);
	for (const a of m.art.animations ?? []) console.log(`    animation   ${a}`);
	for (const s of m.art.screens ?? []) console.log(`    screen      ${s}`);
	if (m.art.note) console.log(chalk.cyan(`    note        ${m.art.note}`));
	console.log('');

	console.log(chalk.bold('  Front end'));
	if (m.frontend.bookEvents?.length) console.log(`    bookEvents  ${m.frontend.bookEvents.join(', ')}`);
	if (m.frontend.components?.length) console.log(`    components  ${m.frontend.components.join(', ')}`);
	if (m.frontend.notes) console.log(chalk.dim(`    ${m.frontend.notes}`));
	console.log('');

	console.log(chalk.bold('  Maths'));
	if (m.math.sample) console.log(`    sample      ${m.math.sample}`);
	if (m.math.notes) console.log(`    ${m.math.notes}`);
	if (m.recipe) console.log(chalk.green(`    generated today by the "${m.recipe}" behavior recipe`));
	console.log('');

	if (m.conflictsWith.length) {
		console.log(chalk.bold('  Conflicts with'));
		for (const c of m.conflictsWith) {
			console.log(`    ${chalk.red(c.id.padEnd(28))}${c.why}`);
		}
		console.log('');
	}
	if (m.combinesWith.length) {
		console.log(chalk.bold('  Combines with'));
		console.log(`    ${m.combinesWith.join(', ')}\n`);
	}
	printSourcing();
	return m;
}

function printArt(requirements) {
	console.log(chalk.bold('\n  Art the team must produce'));
	for (const s of requirements.symbols) console.log(`    symbols   [${s.mechanic}] ${s.requirement}`);
	if (requirements.states.length) console.log(`    states    ${requirements.states.join(', ')}`);
	for (const a of requirements.animations) console.log(`    animation ${a}`);
	for (const s of requirements.screens) console.log(`    screen    ${s}`);
	for (const n of requirements.notes) console.log(chalk.cyan(`    note      [${n.mechanic}] ${n.note}`));
	console.log('');
}

/**
 * Printed on every view, not buried in a doc.
 *
 * The boundary this studio set at the start of the project is the reason the
 * library can exist at all, and it is worth restating wherever the research is
 * read — including by someone who arrives at this output six months from now.
 */
function printSourcing() {
	console.log(
		chalk.dim(
			'\n  Sourced from public marketing pages, provider documentation and review coverage as\n' +
				'  plain-language RULES. No studio\'s assets, bundles, source, sprite data, reel strips or\n' +
				'  RTP configuration were fetched or inspected, and none may be added. We build the\n' +
				'  mechanic ourselves, with our own art. Max-win figures are indicative — spot-check\n' +
				'  anything load-bearing.',
		),
	);
}
